[tool.commitizen]
name = "cz_conventional_commits"
version = "0.6.1"
tag_format = "v$version"
bump_message = "chore(release): bump version $current_version → $new_version"
version_files = [
    "charts/db-provision-operator/Chart.yaml:^version",
    "charts/db-provision-operator/Chart.yaml:^appVersion",
    "mkdocs.yml:version:",
]
