version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    # - goconst  # Disabled: style suggestion for repeated strings
    # - gocyclo  # Disabled: complex reconcile functions are expected in operators
    - govet
    # - ineffassign  # Disabled: false positives in range loops
    - lll
    - misspell
    - nakedret
    # - prealloc  # Disabled: style suggestion for slice allocation
    - revive
    # - staticcheck  # Disabled: deprecation warnings for external APIs
    - unconvert
    # - unparam  # Disabled: unused params needed for interface compliance
    - unused
  settings:
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
